# Run parallel jobs to sum each of the several data.txt.* partial files.

log    =    log/$(Cluster)_$(Process).log
error  =  error/$(Cluster)_$(Process).err
output = output/$(Cluster)_$(Process).out

universe = vanilla
executable = ./process.sh
arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(file)

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue file from file.list
